CREATE TABLE `chmyr`.`user` (
			`ID` INT(10) NOT NULL AUTO_INCREMENT ,
			`NAME` VARCHAR(255) NOT NULL ,
			`SURNAME` VARCHAR(255) NULL ,
			`LOGIN` VARCHAR(255) NOT NULL ,
			`PASSWORD` VARCHAR(255) NOT NULL ,
			`PHOTO` VARCHAR(255) NULL ,
			`COMMENT_ID` INT(11) NULL ,
			PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `chmyr`.`posts` (
			`ID` INT(12) NOT NULL AUTO_INCREMENT ,
			`TITLE` VARCHAR(255) NOT NULL ,
			`DESCRIPTION` VARCHAR(255) NOT NULL ,
			`DATA CREATE` DATE NOT NULL , `DATA UPDATE` DATE NOT NULL ,
			`PHOTO` VARCHAR(255) NULL , `COMMENT_ID` INT(11) NULL ,
			`USER_ID` INT(10) NOT NULL ,
			PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `chmyr`.`comments` (
			`ID` INT(10) NOT NULL AUTO_INCREMENT ,
			`DESCRIPTION` VARCHAR(255) NOT NULL ,
			`DATA_CREATE` DATE NOT NULL ,
			`DATA_UPDATE` DATE NOT NULL ,
			`USER_ID` INT NOT NULL ,
			 PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `chmyr`.`favorite` (
			`USER_ID` INT(10) NOT NULL ,
			`POST_ID` INT(12) NOT NULL ) ENGINE = InnoDB;
CREATE TABLE `chmyr`.`tegs` (
			`ID` INT(13) NOT NULL AUTO_INCREMENT ,
			`NAME` VARCHAR(255) NOT NULL ,
			PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `chmyr`.`post_tegs` (
			`POST_ID` INT(12) NOT NULL ,
			`TEGS_ID` INT(13) NOT NULL ) ENGINE = InnoDB;